### PR TITLE
openssl 1.0.2d

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by eousphoros** [comment]
Thank you

**Comment by PeterDaveHello** [comment]
btw, there is comment and patch for v1.0.1, do we still need it?

**Comment by eousphoros** [comment]
I believe so, its for compiling openssl as a static library. If you can prove me wrong I am all for removing patches if we can.

**Comment by PeterDaveHello** [comment]
I think I can't, just wanna confirm with you :)

**Pull request merged**
